-- ────────────────────────────────────────────────────────────
-- Omarchy Custom Theme for Neovim
-- Generated by Omarchist
-- ────────────────────────────────────────────────────────────

return {
	{
		"bjarneo/aether.nvim",
		name = "aether-ghost-harmonized",
		priority = 1000,
		opts = {
			disable_italics = false,
			colors = {
				-- Monotone shades (base00-base07)
				base00 = "#000000", -- Background (pure black)
				base01 = "#121212", -- UI panels / splits
				base02 = "#1E1E1E", -- Selection / hover
				base03 = "#2A2A2A", -- Comments
				base04 = "#4A4A4A", -- Muted text
				base05 = "#808080", -- Main text
				base06 = "#F5F5F5", -- Bright text / emphasis
				base07 = "#FFFFFF", -- Lightest tone for contrast

				-- Accent colors (base08-base0F)
				base08 = "#2A2A2A", -- Errors
				base09 = "#4A4A4A", -- Constants
				base0A = "#808080", -- Types
				base0B = "#F5F5F5", -- Strings
				base0C = "#1E1E1E", -- Support
				base0D = "#FFFFFF", -- Functions
				base0E = "#F5F5F5", -- Keywords
				base0F = "#121212", -- Deprecated
			},
		},
		config = function(_, opts)
			require("aether").setup(opts)
			vim.cmd.colorscheme("aether")
			require("aether.hotreload").setup()
		end,
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
